baseURL: "https://carlossanabriam.github.io"
languageCode: "en-us"
title: "Carlos Sanabria Miranda"
theme: hugo-profile

# Pagination (https://gohugo.io/templates/pagination/)
Paginate: 3

# Google Analytics (https://gohugo.io/templates/internal/#google-analytics)
#googleAnalytics: G-MEASUREMENT_ID # TODO
# Disqus (https://gohugo.io/templates/internal/#disqus)
#disqusShortname: your-disqus-shortname # TODO

# Markdown and other markup related configuration (https://gohugo.io/getting-started/configuration-markup)
markup:
  goldmark: # Goldmark is from Hugo 0.60 the default library used for Markdown
    renderer:
      unsafe: true # render raw HTMLs

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # Open Graph (https://gohugo.io/templates/internal/#open-graph) and Twitter Cards (https://gohugo.io/templates/internal/#twitter-cards) metadata
  title: "Carlos Sanabria Miranda"
  description: My personal website
#  images: # TODO
#    - site-feature-image.jpg
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    # align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true # Disable search in the navbar, because there is not searchable content yet
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false

  # Documentation for configuring each of the following sections:
  # https://github.com/gurusabarish/hugo-profile/wiki/Pages-or-Sections

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Carlos"
    subtitle: "A passionate Data Engineer"
    content: |-
        I use modern technologies to design, implement, test, deploy, monitor and maintain data driven apps.
        I am specialized in streaming processing and Cloud computing.
    image: /images/hero.png
    socialLinks:
      fontAwesomeIcons:
        # https://fontawesome.com/v5/search
        # Font Awesome icons are designed on grid and share a consistent height.
        # But they vary in width depending on how wide or narrow each symbol is.
        # If you prefer to work with icons that have a consistent width, adding fa-fw will render each icon using the same width.
        # https://fontawesome.com/docs/web/style/fixed-width
        - icon: fab fa-github fa-fw
          url: "https://github.com/CarlosSanabriaM"
        - icon: fab fa-linkedin fa-fw
          url: "https://www.linkedin.com/in/CarlosSanabriaM"
        - icon: fas fa-code-branch fa-fw
          url: "https://github.com/CarlosSanabriaM/carlossanabriam.github.io"
#      customIcons:
#        - icon: /fav.png
#          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      I am a Software Engineer with a strong passion for data and analytics, and the Cloud computing ecosystem.
      I have a solid background in data streaming processing, particularly with Apache Flink, in the AWS cloud.
      I am a strong advocate of the DevOps culture and its benefits, and I cannot imagine a project without CI/CD, automation or monitoring.
      I also have a keen interest in the IoT world and its applications across various fields.

      I have +5 years of experience in the data ecosystem, and I am currently working as a Data Engineer at
      [Openbank](https://www.opendigitalservices.com/) in Spain. I also have some experience in leading
      development teams and teaching online classes.
      
      I was honored with the [Final Degree Award](https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing)
      for the best academic record in the Software Engineer Degree.

      I’m a very curious person, always eager to learn new things and improve myself every day.
      I am very disciplined with my habits, and I always try to do my best to achieve my goals.

      As for my hobbies, I really enjoy staying active and practicing sports, especially going to the gym,
      but I am always open to exploring new sports whenever I can. I like spending time with my friends and my girlfriend,
      watching football, listening to music and podcasts, playing video games, and collecting vinyl records and anime statues.
      I am also an avid reader, particularly of personal development books, manga, and video game magazines.
      I love traveling, experiencing diverse cultures and meeting new people.
    skills:
      enable: true
      title: "These are my essential skills and the technologies in which I have the most expertise:"
      items:
        - "Spanish (native)"
        - "[English (C1)](https://drive.google.com/file/d/1mXeXpdDFqLQ_1aZJO9-XDZZ3W7lqiASE/view?usp=sharing)"
        - "Java"
        - "Python"
        - "Flink"
        - "Kafka"
        - "Iceberg"
        - "Redis"
        - "Docker"
        - "Kubernetes"
        - "Ansible"
        - "Vagrant"
        - "Grafana"
        - "Kibana"
        - "Spring"
        - "AWS"

  # Experience
  experience:
    enable: true
    companies:
      - company: "Accenture"
        companyUrl: "https://www.accenture.com"
        jobs:
          - job: "Advanced App Engineering Senior Analyst - Big Data"
            date: "Dic 2020 - Present"
            info:
              enable: false
            content: |
              * Developed and __end-to-end solution__ for __monitoring__ __Flink__ and __EMR__; which includes the collection, processing and loading of Flink/EMR __metrics__ and __logs__; and the creation of __dashboards__ in __Grafana__ and __Kibana__ for their visualization and analysis.
              * __Automated__ the __configuration__ of the __EMR__ clusters through __Ansible__, following a __GitOps__ philosophy.
              * Implemented a __Continuous Delivery__ pipeline for the deployment of __Flink__ jobs in __EMR__, based on the __declarative__ paradigm.
              * Developed a __proof of concept__ of the new __Flink SQL__ version, to __homologate__ it and promote its usage within the project.
              * Improved and __evolved__ a __Java framework__ based on __Flink__, including abstractions over the new __Flink SQL__ API version, which __simplified the development__ of streaming applications focused on the __joins__ between streams of events.
              * __Reduced__ in a __60\%__ the __costs__ of the __AWS infrastructure__, due to the __analysis__ of the __consumptions__ of the __EMR__ and __ElastiCache__ services, and the __optimization__ of the used __instances__ (number and type of instances, as well as the use of __spot__ instances).
              * Kept a __close contact__ with the development teams of the __client__, focused on the decision making and continuous improvement.
              * Made __guards__ focused on the __maintenance__ of the __production__ applications, __solving__ numerous __incidents__.
              * Was __selected__ by __Accenture__ to take part of the __TechStar__ program (in which  __less than 1%__ of the analysts and consultants of Accenture Technology can participate), and in which I was able to __reinforce__ my __technical__, __soft__ and __management skills__.
              * __Interviewed__ __3 people__ to choose a new member for our project __development team__ (technical interviews).
              * __Lead__ a __team of 3 developers__ to carry out and deploy multiple __projects__ developed in __Flink__.
              * __Participated__ in a __RFP__ (Request For Proposals) for one of the largest insurance companies in the market, in which I __designed__ a __serverless microservices architecture__ on __AWS__, with high and low level diagrams, which was a complete __success__, given the fact that __the project was awarded to Accenture__, and we received the __direct greetings from the CDO__ of the insurance company.

          - job: "Advanced App Engineering Analyst - Big Data"
            date: "May 2019 - Dic 2020"
            info:
              enable: false
            content: |
              * Designed and implemented a __Java framework based on Apache Flink__ which eased the development of __Big Data applications for processing events in real time__, that abstracts the following components: security configurations, read/write events from/to Kafka, N-N joins among events, generation of custom metrics, timestamps management, ...
              * Implemented and deployed in __AWS__ multiple __streaming applications__ employing the previous framework, using services such as __EMR, S3, ElastiCache, EC2 and Certificate Manager__, and technologies such as __Kafka, Redis, CouchBase y Hadoop YARN__.
              * Implemented multiple __scripts in Python and Bash__ for automating processes.
              * Contributed to the adoption of a __testing culture__ focused on specification-based techniques (__Equivalent Class Partitioning__) and structure-based techniques (__MCDC - Modified condition/decision coverage__).
              * Took part of a __multidisciplinary development team__, guided by __Agile methodologies__, and focused in the __continuous integration__ (version control with __Git and GitLab__, __code reviews__ through Merge Requests, __Jenkins__, __SonarQube__ and __Artifactory__).

          - job: "Intern in Artificial Intelligence"
            date: "Feb 2019 - May 2019"
            featuredLink:
              enable: true
              name: "Project website"
              url: "http://topics-and-summary-web-front.herokuapp.com"
            info:
              enable: true
              content: The project I worked on in this internship was presented as my final degree project.
            content: |
              * Developed a library for the __identification of topics__ present in a collection of documents, the __classification of documents__ in those topics, and the __generation of extractive text summaries__, using Natural Language Processing techniques (__NLP__), by means of supervised and unsupervised learning, in the __Python__ programming language.
              * Developed a __REST API in Flask__ and a __frontend in Angular__ which eased the interaction with a collection of documents.

      - company: "UniOvi"
        companyUrl: "https://www.uniovi.es"
        jobs:
          - job: "Computer Science Intern"
            date: "Oct 2017 - May 2018"
            info:
              enable: true
              content: Universidad de Oviedo
            content: |
              * __Installed__ diverse __software__ packages and __repaired__ multiple __hardware__ equipments. __Managed the inventory__. __Solved problems__ of various kinds, both from students and teachers (where stood out the problems related to the __Active Directory__).

  # Education
  education:
    enable: true
    items:
      - title: "Bachelor's Degree in Software Engineering"
        school:
          name: "Universidad de Oviedo"
          url: "https://ingenieriainformatica.uniovi.es/infoacademica/grado"
        date: "2015–2019"
        GPA: "9.312 out of 10 · 3.66 out of 4"
        content: |-
          * __Awarded 28 honors__
          * __Final Degree Award for best academic record__
          * __Grace Hopper Award for academic excellence__
          * __Final Degree Project__: Web application for the classification of text documents and the generation of extractive summaries
            * [Source code](https://github.com/CarlosSanabriaM/degree-final-project)
            * [Website](http://topics-and-summary-web-front.herokuapp.com)
        featuredLink:
          enable: true
          name: "Final Degree Award"
          url: "https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing"

  # Achievements
  achievements:
    enable: true
    items:
      - title: AWS Certified Cloud Practitioner
        url: "https://www.credly.com/badges/ac01d725-09f7-474c-980b-7d23c952a202/public_url"
        image: /images/certifications/aws-certified-cloud-practitioner.png
        imageWidthPercentage: 50%
        content: July 2020
      
      - title: AWS Certified Solutions Architect – Associate
        url: "https://www.credly.com/badges/cc930e4d-3b8b-4c81-b59a-068efffc6778/public_url"
        image: /images/certifications/aws-certified-solutions-architect-associate.png
        imageWidthPercentage: 50%
        content: March 2021
      
      - title: AWS Certified Data Analytics – Specialty
        url: "https://www.credly.com/badges/a25d383c-e9dc-4615-87c0-3248cca98b1b/public_url"
        image: /images/certifications/aws-certified-data-analytics-specialty.png
        imageWidthPercentage: 50%
        content: July 2021
      
      - title: "Microsoft Certified: Azure Fundamentals"
        url: "https://www.credly.com/badges/11094dde-fba8-4151-97a4-620312171991/public_url"
        image: /images/certifications/microsoft-certified-azure-fundamentals.png
        imageWidthPercentage: 50%
        content: November 2020
      
      - title: "Microsoft Certified: Azure Data Fundamentals"
        url: "https://www.credly.com/badges/27ef3e46-2484-4337-8edb-34162d412e60/public_url"
        image: /images/certifications/microsoft-certified-azure-data-fundamentals.png
        imageWidthPercentage: 50%
        content: January 2021
      
      - title: Certified Kubernetes Application Developer
        url: "https://www.credly.com/badges/641ae1d8-6742-4fd0-887a-76cf394114c2/public_url"
        image: /images/certifications/ckad-certified-kubernetes-application-developer.png
        imageWidthPercentage: 50%
        content: April 2022

      - title: Accenture TechStar 2022
        content: |-
          I was selected by Accenture to participate in the exclusive TechStar program,
          where I had the opportunity to further develop my technical, interpersonal, and management skills.
        url: "https://www.linkedin.com/pulse/accenture-technology-stars-2018-sam-liew/"

      - title: Final Degree Award
        content: I received this award for achieving the best academic record (the highest GPA) in my cohort for the Bachelor's Degree in Software Engineering.
        url: "https://drive.google.com/file/d/1krHMfnayADHeWNg5gBrqJwiVuEcmiIC1/view?usp=sharing"

      - title: Grace Hopper Award
        content: I received this award in recognition of my academic excellence in the Bachelor's Degree in Software Engineering.

  # Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:sanabria.miranda.carlos@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  # Footer
  footer:
    #recentPosts: false # TODO: Uncomment when posts are available
    socialNetworks:
      github: "https://github.com/CarlosSanabriaM"
      linkedin: "https://www.linkedin.com/in/CarlosSanabriaM"
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
